### ISSUE TITLE
Define how to add new Requierements

### ISSUE THREAD

**Issue by simhein** [zephyrproject-rtos/reqmgmt#13]
Describe how new requirements can be added and what needs to be considered when adding new requirements

Following additional information should be defined and described to describe the addition of new requirements properly:
- [ ] Explain the fields we use and the meaning of the fields
- [ ] Explain the status and who changes it
- [ ] Explain Relations of requirements and which are used
- [ ] Explain acceptance criteria of a requirement
- [ ] Describe the commit message layout
	- only needs to be described if we differ from : https://docs.zephyrproject.org/latest/contribute/guidelines.html#commit-message-guidelines

If something is missing in the list feel free to extend it

**Comment by Timotheous** [comment]
Compared the checklist above and the PR.
The requirements fields as defined in the SGRA files are not explained.
That could be added somewhere.  If not now, in a following PR.
