### ISSUE TITLE
Semaphore Requirements

### ISSUE THREAD

**Issue by simhein** [zephyrproject-rtos/reqmgmt#18]
Populate / extend the requirements documents with semaphore requirements.

**Comment by nicpappler** [comment]
- [ ] analyse existing requirements in the Zephyr High Level Requirements and Functional Requirements sdoc files regarding completeness to the associated sources (sem.c)
- [ ] add the requirements to the sections associated with Semaphores in the sdoc files, if no section exists, add new section
- [ ] establish linking from Functional to High Level Requirements, using sdoc functionality

**Comment by simhein** [comment]
Introduced with: https://github.com/zephyrproject-rtos/reqmgmt/pull/30
