### ISSUE TITLE
Define UID Naming Conventions

### ISSUE THREAD

**Issue by nicpappler** [zephyrproject-rtos/reqmgmt#7]
We need to define and agree naming and numbering conventions that we use across the specifications and requirements.
The UID names shall represent:

1. a Zephyr specific acronym, like the "ZEP" that we are currently using
2. Level of Requirements - e.g. high level, component level, design, architecture, test spec etc
3. Decimal number, like 001 or 0001 or 0003

For a starting point we should use the numbering scheme presented in the working group on September 12, 2023

**Comment by simhein** [comment]
Safety WG consensus from WG meeting on 10 October 2023: The Zephyr acronym ZEP is used with a numbering only like ZEP-1
That makes moving of requirements between documents easier. The Component and level shall be described in an extra field and not in the UID
